; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; upload_speed = 9600
; upload_resetmethod = nodemcu
; upload_flags = --no-stub
; board_build.flash_mode = dio
; board_build.flash_freq = 40m
; board_upload.flash_size = 4MB

lib_deps =
  adafruit/Adafruit MPRLS Library
  adafruit/Adafruit BusIO
  duinowitchery/hd44780
  paulstoffregen/XPT2046_Touchscreen
  bodmer/TFT_eSPI

build_flags =
  -D USER_SETUP_LOADED
  -D ST7796_DRIVER
  -D TFT_MOSI=23
  -D TFT_MISO=-1
  -D TFT_SCLK=18
  -D TFT_CS=5
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=27
  -D TOUCH_CS=33
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=20000000
  -D LOAD_GLCD
  -D LOAD_FONT2
  -D LOAD_FONT4
  -D LOAD_FONT6
  -D LOAD_FONT7
  -D LOAD_FONT8
  -D LOAD_GFXFF
  -D TFT_INVERSION_ON