; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit MPRLS Library
  Wire
  hd44780
  https://github.com/PaulStoffregen/XPT2046_Touchscreen
  https://github.com/Bodmer/TFT_eSPI


build_flags =

  -D USER_SETUP_LOADED
  -D ST7796_DRIVER   ; probably ILI9341, not ST7789

  -D TFT_MOSI=13
  -D TFT_MISO=12
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1      ; using EN (shared with ESP32 reset)
  -D TFT_BL=27

  -D TFT_WIDTH=240
  -D TFT_HEIGHT=320
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=20000000

  -D LOAD_GLCD
  -D LOAD_FONT2
  -D LOAD_FONT4
  -D LOAD_FONT6
  -D LOAD_FONT7
  -D LOAD_FONT8
  -D LOAD_GFXFF

  -D TFT_INVERSION_ON

